server:
  port: 8000

spring:
  application:
    name: light-common
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    druid:
      url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&useSSL=false
      username: root
      password: 123456
      # 数据库连接池
#      initial-size:
#      max-active:
#      min-idle:
#      max-wait:
#      pool-prepared-statements:
#      max-pool-prepared-statement-per-connection-size:
#      # 和上面的等价
#      max-open-prepared-statements:
#      validation-query:
#      validation-query-timeout:
#      test-on-borrow:
#      test-on-return:
#      test-while-idle:
#      time-between-eviction-runs-millis:
#      min-evictable-idle-time-millis:
#      max-evictable-idle-time-millis:
#      filters:
      # 监控配置
      # WebStatFilter配置，说明请参考Druid Wiki，配置_配置WebStatFilter
#      web-stat-filter:
#        enabled: true
#        url-pattern:
#        exclusions:
#        session-stat-enable:
#        session-stat-max-count:
#        principal-session-name:
#        principal-cookie-name:
#        profile-enable:
      # StatViewServlet配置，说明请参考Druid Wiki，配置_StatViewServlet配置
      #是否启用StatViewServlet（监控页面）默认值为false（考虑到安全问题默认并未启动，如需启用建议设置密码或白名单以保障安全）
#      stat-view-servlet:
#        enabled: true
#        url-pattern:
#        reset-enable:
#        login-username:
#        login-password:
#        allow:
#        deny:
