server:
  port: 8700

spring:
  application:
    name: light-mini-app
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

management:
  endpoints:
    web:
      exposure:
        include: *

